name: Dump Entities from Baserow

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
        DB_USER: root
        DB_PW: donauhandel
        DB_NAME: donauhandj87mysql11
        DB_HOST: 0.0.0.0
        DB_PORT: 3307

    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: set up mariadb
        run: source dl_dumps.sh
      - name: dump the data
        run: python scripts/sql_to_csv.py
      - name: merge the data
        run: python scripts/merge_person_table.py
      - name: convert to TEI/XML
        run: |
          python scripts/create_listperson.py
          python scripts/create_listplace.py
          python scripts/create_listorg.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Data update from Baserow
