name: Dump Entities from Baserow

on:
  schedule:
    - cron: "12 3 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v4
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: set up mariadb
        run: source dl_dumps.sh
      - name: convert the data
        run: python scripts/sql_to_csv.py
      - name: merge the data
        run: python scripts/merge_person_table.py
      - name: convert to TEI/XML
        run: python scripts/create_teis.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Data update from Baserow
